### ISSUE TITLE
Rpm provider fails when package is already installed

### ISSUE THREAD

**Issue by rorist** [treydock/puppet-module-nhc#1]
Hi,

When using the rpm provider instead of the yumrepo, it fails because the package name isn't what is expects.

For instance when installing from this url, it gives me that,
`Error: Execution of '/bin/rpm -i http://warewulf.lbl.gov/downloads/repo/rhel6/warewulf-nhc-1.4.1-1.el6.noarch.rpm' returned 1: package warewulf-nhc-1.4.1-1.el6.noarch is already installed`

One possible solution would be to make the package name parameterized depending on the provider.
https://github.com/treydock/puppet-module-nhc/blob/master/manifests/install.pp#L7

I'll propose a PR.
Regards

**Comment by treydock** [comment]
This module is intended to be used with NHC not associated directly with warewulf.  The packages I test against are here , https://github.com/mej/nhc/releases

I copied most of this module from my previous module here, https://github.com/treydock/puppet-module-warewulf.  The warewulf module will work with the package your trying to use but I've since moved to using this module as I only use NHC, not warewulf.

A parameterized approach would be good too.  Could possibly base off version if NHC >= 1.4.2 only exists outside warewulf repos.
